### ISSUE TITLE
Extending Documentation (README.md)

### ISSUE THREAD

**Issue by jeromewagener** [davesade/luxtrain#13]
Hi Dave,

As discussed, I am going to extend the documentation a bit in order to distribute the information between my collegues. You will be able to see what I am doing in the forked repository that I am going to create.

Please let me know if you have any question, issue or concern. :smile: 

Kind regards,
Jérôme

**Comment by davesade** [comment]
@jeromewagener That is very kind of you, thanks. I will add you to our unofficial @do-team, because some things we do, are actually starting on github.com. Nothing major, Enterprise server should be single point of information anyway.

**Comment by davesade** [comment]
@jeromewagener  I have moved this repository to our Enterprise server, search within forks for cookbook. No more updates expected here on github.com .

**Comment by jeromewagener** [comment]
@davesade thanks for your message and sorry for my late reply. (I / We were quite busy the last weeks) Just for info, We migrated almost all our VOBs to Git and people are starting to get accustomed to GitHub enterprise. Its quite a change, but a welcomed one! :-) Thanks for all your help!
